// Generated by LiveScript 1.2.0
(function(){
  var express, app, Poet, contact, bodyParser, poet;
  express = require('express');
  app = express();
  Poet = require('poet');
  app.set('view engine', 'jade');
  app.set('views', __dirname + '/views');
  app.use(express['static'](__dirname + '/public'));
  app.get('/rss', function(req, res){
    var posts;
    posts = poet.helpers.getPosts(0, 5);
    res.setHeader('Content-Type', 'application/rss+xml');
    return res.render('rss', {
      posts: posts
    });
  });
  contact = require('./mail/contact');
  bodyParser = require('body-parser');
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({
    extended: true
  }));
  app.post('/contact', function(req, res){
    console.log('Request', req.body);
    return contact(req, function(result){
      return res.json({
        result: result
      });
    });
  });
  poet = Poet(app, {
    metaFormat: 'yaml',
    postsPerPage: 5
  });
  poet.addRoute('/posts', function(req, res){
    var page, lastPost;
    page = 1;
    lastPost = page * 3;
    return res.render('page', {
      posts: poet.helpers.getPosts(lastPost - 3, lastPost),
      page: page
    });
  });
  poet.init().then(function(){
    console.log('poet initialized');
    console.log(Object.keys(poet.posts));
    return done();
  });
  module.exports = app;
}).call(this);
