// Generated by LiveScript 1.2.0
(function(){
  var nodemailer, fs, configFile, fileJson, err, mailConfig, smtpTransport, options, mail, validated, msgFor, sendEmail;
  nodemailer = require('nodemailer');
  fs = require('fs');
  configFile = 'config/mail-config.json';
  try {
    fileJson = fs.readFileSync(configFile);
  } catch (e$) {
    err = e$;
    console.error(err);
  }
  mailConfig = JSON.parse(fileJson);
  console.log('using mail-config:', mailConfig);
  mailConfig.auth.pass = process.env.mailpass;
  mailConfig.auth.user = process.env.mailuser;
  smtpTransport = nodemailer.createTransport(mailConfig);
  smtpTransport.on('log', console.log);
  options = {
    me: 'kmandrup@gmail.com'
  };
  mail = function(body){
    return {
      from: body.name + ' <' + body.email + '>',
      to: options.me,
      subject: body.subject || 'Infomatrix Contact',
      text: body.message
    };
  };
  validated = function(body){
    if (body.name && body.email && body.subject && body.message) {
      return true;
    }
    return false;
  };
  msgFor = function(err){
    if (err) {
      return 'Error occured, message not sent.';
    } else {
      return 'Message sent! Thank you.';
    }
  };
  sendEmail = function(req, callback){
    var body, options;
    console.log('send email Request:', req);
    body = req.body;
    console.log('Body:', body);
    if (!validated(body)) {
      return callback();
    }
    options = mail(body);
    console.log('with options', options);
    return smtpTransport.sendMail(options, function(error, info){
      var err;
      err = !!error;
      console.log('mail result', err, info);
      return callback(err);
    });
  };
  module.exports = sendEmail;
}).call(this);
